### DISCUSSION TITLE
分享自定义的译文样式

### DISCUSSION THREAD

**Discussion by lmk123** [hcfyapp/crx-selection-translate#1686] [讨论]
划词翻译 v9.7.0 添加了一个新的选项“自定义译文样式”，可以使用 [CSS](https://developer.mozilla.org/zh-CN/docs/Web/CSS) 自定义全文翻译功能中译文的样式。欢迎大家在这个帖子里分享自己的自定义样式，好看的样式我会考虑直接加入到划词翻译当中。

**Comment by ixxc** [comment]
简单的调了下颜色，在黑色主题下也方便阅读

```css
.__hcfy-result-comparison__ {
}
.__hcfy-result-comparison__ hcfy-result-content {
  /* 译文内容样式 */
  color: #ffffff;
  background: linear-gradient( to right, rgba(0, 128, 128, 0.6), rgba(0, 140, 128, 0.8) 2%, rgba(0, 128, 135, 0.9) 35%, rgba(0, 150, 128, 0.9) 70%, rgba(0, 128, 100, 0.8) 95%, rgba(0, 128, 128, 0.6) );
  box-decoration-break: clone;
  -webkit-box-decoration-break: clone;
}
.__hcfy-result-editing__ {
}
.__hcfy-result-comparison-block__ {
}
.__hcfy-result-comparison-inline__ {
}
```

![image](https://user-images.githubusercontent.com/105781599/227853845-2dc17db6-e2f5-4e0e-8eb2-8f3591ba0b52.png)
![image](https://user-images.githubusercontent.com/105781599/227853880-b21f6401-d9f1-4433-bf93-bea84ef64453.png)

**Comment by FuuuOverclocking** [comment]
推荐下我的样式：
```css
.__hcfy-result-comparison__ {
  /* 译文外框样式 */
}
.__hcfy-result-comparison__ hcfy-result-content {
  background: #DEDEDF;
  border-radius: 6px;
  padding: .1em .25em;
  color: black;
}
.__hcfy-result-editing__ {
  /* 译文处于编辑状态时的样式 */

  /* 我禁止了编译译文*/
}
.__hcfy-result-comparison-block__ {
  /* 译文跟原文是换行显示时的样式 */
}
.__hcfy-result-comparison-inline__ {
  /* 译文跟原文是同一行显示时的样式 */
}
```

效果：

![image](https://user-images.githubusercontent.com/32507398/230555859-2f564115-dfb3-4b6e-99bd-9e5c3999918b.png)

![image](https://user-images.githubusercontent.com/32507398/230555874-05e6be53-da2c-4708-baa1-886b9615c620.png)

**Comment by yhm-amber** [comment]
一个（在 CSS 代码以及它的效果上都）尽可能简洁的样式。

~~~ css
hcfy-result{--hcfy-result-main-color:#cf77ff;}
.__hcfy-result-comparison__ 
{
  border-left: 5px solid var(--hcfy-result-main-color);
  padding-left: 6px;
}
.__hcfy-result-comparison-block__ { padding: 6px 0 6px 12px; }
.__hcfy-result-comparison-inline__ { margin-left: 0.4em; }
~~~

翻译块使用了引用样式。

尽可能减少不必要的代码。删掉了默认文字颜色的设定，因此文字颜色会自动跟随相应段落文字的颜色。没有编辑时的样式。适合用于页面离线保存（比如与 SingleFile 一起）。

其中的 `cf77ff` 是一个很骚（指醒目）的紫色。你也可以替换为你想要的颜色。

![image](https://user-images.githubusercontent.com/103625580/232986747-abf86f19-7861-417a-b718-520b86a6f99d.png)

**Comment by loveloki** [comment]
提供一个默认隐藏，浮动和编辑状态下再显示的方案。

```CSS
/* 根元素样式 */
hcfy-result {
  --hcfy-highlight-color: #f2ae49;
  --hcfy-tip-color: f3f4f5;
  --hcfy-left: 16px;
  border-radius: 8px;
}

/* 译文外框样式 */
.__hcfy-result-comparison__ {
  border-left: 5px solid var(--hcfy-highlight-color);
  border-right: 5px solid var(--hcfy-highlight-color);
  padding: 10px 8px;
  margin-top: 4px;
  margin-left: var(--hcfy-left);
}

/* 译文处于编辑状态时的样式 */
.__hcfy-result-editing__ {
  border-color: #ffff;
  outline: 5px solid var(--hcfy-highlight-color);
}


/* 译文内容样式，默认隐藏  */
.__hcfy-result-comparison__ hcfy-result-content {
  opacity: 0;
  outline: none;
  transition: opacity 0.15s ease;
}

/* 鼠标悬浮和编辑模式取消隐藏*/
hcfy-result:hover hcfy-result-content, .__hcfy-result-editing__ hcfy-result-content  {
  opacity: 1;
}
```


默认情况下：

![image](https://github.com/hcfyapp/crx-selection-translate/assets/14935777/75e9730a-a6be-4676-b40f-d14345bd09f9)

鼠标浮动上去：

![image](https://github.com/hcfyapp/crx-selection-translate/assets/14935777/487f99e4-614f-4080-89dc-90d04e5f1a68)

编辑状态：

![image](https://github.com/hcfyapp/crx-selection-translate/assets/14935777/23baab26-0a6d-4256-a3ed-02e591c7928b)
