### ISSUE TITLE
突出显示译文只是加个框框太简陋了

### ISSUE THREAD

**Issue by ghost** [hcfyapp/crx-selection-translate#1624]
希望可以对“原文”“译文”有更多自定义项目，比如**字体 颜色。或者加入下划线等等。。。**。这样能有更多区分

**Comment by lmk123** [comment]
我也知道很简陋，但以我的设计水平，我实在不知道要怎么设计才能让这个对比在所有网站中都合适 :joy:

不同的网站会使用不同的背景颜色、字体颜色、排版等，我不知道该怎么设计

**Comment by ghost** [comment]
> 

让用户自己设置啊

**Comment by lmk123** [comment]
可以，我预先设定多种样式，然后让用户自己选吧

**Comment by ixxc** [comment]
这功能确实需要，预设一些样式给用户选择就好了，尤其在文字很多的网页下加个简简单单的底色就能极大地提升阅读体验，比如类似这种：
![image](https://user-images.githubusercontent.com/105781599/226166608-7d4cf7ac-051f-442a-8fb8-ed3f7f672302.png)

**Comment by Dylan-ZQL** [comment]
可以参考最近挺火的沉浸式翻译插件的样式和实现方法，其中的“引用样式”很舒服。
<img width="603" alt="屏幕截图 2023-03-21 144526" src="https://user-images.githubusercontent.com/61696620/226535561-47155078-8150-4f9f-b909-334b8a75bcce.png">

[https://github.com/immersive-translate/immersive-translate](url)
而且，如果所有译文都突出显示也不是多好看，例如一些标题和按钮

**Comment by FuuuOverclocking** [comment]
默认的太难看了，推荐下我的样式：
```css
.__hcfy-result-comparison__ {
  /* 译文外框样式 */
}
.__hcfy-result-comparison__ hcfy-result-content {
  background: #DEDEDF;
  border-radius: 6px;
  padding: .1em .25em;
  color: black;
}
.__hcfy-result-editing__ {
  /* 译文处于编辑状态时的样式 */

  /* 我禁止了编译译文*/
}
.__hcfy-result-comparison-block__ {
  /* 译文跟原文是换行显示时的样式 */
}
.__hcfy-result-comparison-inline__ {
  /* 译文跟原文是同一行显示时的样式 */
}
```

效果：

![image](https://user-images.githubusercontent.com/32507398/230555386-48e61ffa-89e6-4ad6-87b1-37dd2356214b.png)

![image](https://user-images.githubusercontent.com/32507398/230555412-c9c8f04c-7744-42f0-b762-3ff600198097.png)
